name: 和风天气博客
brand: 和风天气
description: 和风天气官方博客和新闻站点
timezone: Asia/Shanghai
url: https://blog.qweather.com
lang: zh
logo: https://cdn.qweather.com/media/qw-logo-s-dark-800.png
attribution: qweather.com
github: https://github.com/qwd/blog/
icp:
  number: 京ICP备15048401号-11
  url: "https://beian.miit.gov.cn"
nis:
  number: 京公网安备11010502042548号
  url: http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=11010502042548
webmaster_verifications:
  google: WFu5M6w9XiYrf3hgUBLxCA1Jrgb_CWTzXTPycVIqngg
  bing: EDFBFE217D2B905D82BE1D5A1BC9AB28
  baidu: code-4479XEvxP0

excerpt_separator: <!-- more -->
paginate: 9

defaults:
  - scope:
      path: pages
      type: pages
    values:
      layout: html
      lang: zh
      seo:
        type: webpage
  - scope:
      path: _posts
      type: posts
    values:
      layout: blog
      lang: zh
      is_post: true
      permalink: "/post/:slug/"
sass:
  sass_dir: _sass
  style: compressed

exclude:
- CNAME
- README.md
- LICENSE
- test

plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-redirect-from
- jekyll-paginate
